config/routes.rb
Rails.application.routes.draw do
  resources :influencers do
    resources :lists
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/influencer.rb
class Influencer < ApplicationRecord
  has_many :lists
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :influencer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController
  before_action :set_influencer, only: %i[show edit update destroy]

  def index
    @influencers = Influencer.order('RANDOM()').limit(15)
  end

  def show; end

  def new
    @influencer = Influencer.new
  end

  def edit; end

  def create
    @influencer = Influencer.new(influencer_params)

    respond_to do |format|
      if @influencer.save
        format.html { redirect_to @influencer, notice: 'Influencer was successfully created.' }
        format.json { render :show, status: :created, location: @influencer }
      else
        format.html { render :new }
        format.json { render json: @influencer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @influencer.update(influencer_params)
        format.html { redirect_to @influencer, notice: 'Influencer was successfully updated.' }
        format.json { render :show, status: :ok, location: @influencer }
      else
        format.html { render :edit }
        format.json { render json: @influencer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @influencer.destroy
    respond_to do |format|
      format.html { redirect_to influencers_url, notice: 'Influencer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_influencer
    @influencer = Influencer.find(params[:id])
    @lists = List.where influencer_id: @influencer.id
  end

  def influencer_params
    params.require(:influencer).permit(:name, :image, :bio)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @influencer = Influencer.find(params[:influencer_id])
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  def edit; end

  def create
    @influencer = Influencer.find(params[:influencer_id])
    @list = @influencer.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to [@influencer, @list], notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to [@influencer, @list], notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to influencer_path(@influencer), notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_list
    @influencer = Influencer.find(params[:influencer_id])
    @list = @influencer.lists.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/influencers/_form.html.erb
<%= form_with(model: influencer, local: true) do |form| %>
  <% if influencer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(influencer.errors.count, "error") %> prohibited this influencer from being saved:</h2>

      <ul>
      <% influencer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :influencer_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :influencer_image %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :influencer_bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/influencers/edit.html.erb
<h1>Editing Influencer</h1>

<%= render 'form', influencer: @influencer %>

<%= link_to 'Show', @influencer %> |
<%= link_to 'Back', influencers_path %>

app/views/influencers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Influencers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @influencers.each do |influencer| %>
      <tr>
        <td><%= influencer.name %></td>
        <td><img src="<%= influencer.image %>" ></td>
        <td><%= influencer.bio %></td>
        <td><%= link_to 'Show', influencer %></td>
        <td><%= link_to 'Edit', edit_influencer_path(influencer) %></td>
        <td><%= link_to 'Destroy', influencer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Influencer', new_influencer_path %>

app/views/influencers/new.html.erb
<h1>New Influencer</h1>

<%= render 'form', influencer: @influencer %>

<%= link_to 'Back', influencers_path %>

app/views/influencers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @influencer.name %>
</p>

<p>
  <img src="<%= @influencer.image %>" >
</p>

<p>
  <strong>Bio:</strong>
  <%= @influencer.bio %>
</p>

<p>
  <strong>To-don`t lists:</strong>
  <% @lists.each do |list| %>
    <p> • <%= list.body %>
    <%= link_to 'Edit', edit_influencer_list_path(@influencer) %>
    <%= link_to 'Delete', [list.influencer, list], method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</p>


<%= link_to 'Edit', edit_influencer_path(@influencer) %> |
<%= link_to "Create to-don`t list for #{@influencer.name}", new_influencer_list_path(@influencer) %> |
<%= link_to 'Back', influencers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>At2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for([@influencer, @list]) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :list_body%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', influencer_path(@influencer) %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.influencer.name %></td>
        <td><%= list.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'All Influencers', influencers_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', influencer_path(@influencer) %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @list.body %>
</p>

<%= link_to 'Edit', edit_influencer_list_path(@list) %> |
<%= link_to 'Back', influencer_path(@influencer) %>